version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/innovacion_fp
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.18
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=innovacion_fp

volumes:
  mongodb_data:
